RobertaStone/Controllers/ConversationPartnerController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using RobertaStone.Models;

namespace RobertaStone.Controllers
{
    public class ConversationPartnerController : Controller
    {
        // GET: ConversationPartner
        public ActionResult Index()
        {
            var conversationPartner = GetConversationPartners();

            return View(conversationPartner);
        }

        private IEnumerable<ConversationPartner> GetConversationPartners()
        {
            return new List<ConversationPartner>
            {
                new ConversationPartner
                {
                    ConversationPartnerId        =  1,
                    PartnerFirstName             = "Stephane",
                    PartnerLastName              = "Baener"
                },
                new ConversationPartner
                {
                    ConversationPartnerId        = 2,
                    PartnerFirstName             = "Amelie",
                    PartnerLastName              = "Dupoint"
                }
            };
        }

        public ActionResult Details(int id)
        {
            var conversationPartner = GetConversationPartners().SingleOrDefault(c => c.ConversationPartnerId == id);

            if (conversationPartner == null)
                return HttpNotFound();

            return View(conversationPartner);
        }
    }
}

RobertaStone/Controllers/LanguageController.cs
using System.Linq;
using System.Web.Mvc;
using RobertaStone.Models;

namespace RobertaStone.Controllers
{
    public class LanguageController : Controller
    {
        private ApplicationDbContext _context;

        public LanguageController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ViewResult AvailableLanguage()
        {
            var languages =_context.Languages;

            return View(languages);
        }
    }
}

RobertaStone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Roberta Stone</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
@Html.Partial("_NavBar")
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Roberta Stone</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

RobertaStone/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Roberta Stone", "ShowLexis", "Lexis", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Conversation Partners", "Index", "ConversationPartner")</li>
                <li>@Html.ActionLink("Languages", "AvailableLanguage", "Language")</li>
                <li>@Html.ActionLink("Create Lexis", "New", "Lexis")</li>

            </ul>
        </div>
    </div>
</div>